# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "C:/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake" CACHE "FILEPATH" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "C:/Qt/6.4.1/android_armv7/bin/qmake.bat" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "C:/Qt/6.4.1/android_armv7" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "C:/Users/rosep/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "C:/Users/rosep/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" CACHE "FILEPATH" "" FORCE)
set("ANDROID_NATIVE_API_LEVEL" "23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "C:/Users/rosep/AppData/Local/Android/Sdk/ndk/23.1.7779620" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "C:/Users/rosep/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_ABI" "armeabi-v7a" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "C:/Qt/6.4.1/android_armv7" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "C:/Qt/6.4.1/mingw_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "C:/Users/rosep/AppData/Local/Android/Sdk" CACHE "PATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)